import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as vm from 'node:vm';
import { conversationHtml } from '../src/ui/conversation';

test('composer prevents duplicate sends, respects IME/newlines and preserves per-thread drafts', () => {
  const nodes = new Map<string, any>();
  const node = () => ({ value: '', textContent: '', style: {}, children: [] as any[], scrollHeight: 100, scrollTop: 0, clientHeight: 100, append(...items: any[]) { this.children.push(...items); }, replaceChildren() { this.children = []; }, getBoundingClientRect() { return {left:20,top:600}; }, togglePopover() {}, hidePopover() {}, matches() { return true; }, focus() {}, select() {}, showModal() {}, close() {}, querySelector() { return { focus() {} }; }, setAttribute(name: string, value: string) {} });
  const get = (id: string) => { if (!nodes.has(id)) nodes.set(id, node()); return nodes.get(id); };
  const sent: any[] = []; let receive!: (event: any) => void;
  const script = [...conversationHtml().matchAll(/<script nonce="[^"]+">([\s\S]*?)<\/script>/g)].map(match => match[1]).join("\n");
  vm.runInNewContext(script, { acquireVsCodeApi: () => ({ postMessage: (message: any) => sent.push(message) }), document: { getElementById: get, createElement: node }, window: { addEventListener: (type: string, callback: typeof receive) => { if (type === 'message') receive = callback; } } });
  const state = (id: string, busy = false) => receive({ data: { type: 'state', root: 'repo', mode: 'Review', busy, threads: [{ id, name: id }], thread: { id, status: 'idle', messages: [{ role: 'assistant', content: '**Safe** `code` <img src=x onerror=alert(1)>' }] } } });
  assert.ok(!conversationHtml().includes('permissionCustom'));
  receive({ data: { type: 'state', startupToken: 'initial-state', root: 'repo', mode: 'Review', busy: false, threads: [], thread: { id: 'one', name: 'One', messages: [] } } });
  assert.equal(sent.at(-1).type, 'startupAck'); assert.equal(sent.at(-1).token, 'initial-state');
  receive({ data: { type: 'state', startupToken: 'broken-state', thread: null } });
  assert.equal(sent.at(-1).type, 'startupError'); assert.ok(!sent.some(m => m.type === 'startupAck' && m.token === 'broken-state'));
  receive({ data: { type: 'choice', id: 'approval', question: 'Delete <file>?', choices: ['Cancel', 'Approve'] } });
  assert.equal(get('choiceTitle').textContent, 'Delete <file>?');
  get('choiceItems').children[1].onclick();
  assert.deepEqual(JSON.parse(JSON.stringify(sent.at(-1))), { type: 'choiceReply', id: 'approval', index: 1 });
  receive({ data: { type: 'choice', id: 'cancel', question: 'Choose repository', choices: ['repo'] } });
  get('choiceDialog').oncancel({ preventDefault() {} });
  assert.equal(sent.at(-1).index, null);
  state('one'); get('input').value = 'Repair this'; get('input').oninput();
  let prevented = 0;
  const key = (extra: object) => get('input').onkeydown({ key: 'Enter', preventDefault: () => { prevented++; }, ...extra });
  key({ shiftKey: true }); key({ isComposing: true }); key({ keyCode: 229 });
  assert.equal(sent.filter(m => m.type === 'send').length, 0); assert.equal(prevented, 0);
  key({}); key({}); assert.equal(sent.filter(m => m.type === 'send').length, 1); assert.equal(get('input').value, '');
  get('input').value = 'Follow-up draft'; get('input').oninput(); state('one', true);
  assert.equal(get('input').value, 'Follow-up draft'); assert.equal(get('cancel').hidden, false);
  get('cancel').onclick(); assert.equal(sent.at(-1).type, 'cancel');
  state('one'); state('two'); assert.equal(get('input').value, '');
  get('input').value = 'Other draft'; get('input').oninput(); state('one'); assert.equal(get('input').value, 'Follow-up draft');
  get('permissions').onclick(); get('permissionReview').onclick(); assert.equal(sent.at(-1).type, 'permissions'); assert.equal(sent.at(-1).mode, 'Review');
  get('model').onclick(); assert.equal(sent.at(-1).type, 'selectModel');
  get('settings').onclick(); assert.equal(sent.at(-1).type, 'settings');
  assert.equal(sent.find(m => m.type === 'send').newConversation, true);
  get('rename').onclick(); get('renameInput').value = 'Renamed'; get('renameForm').onsubmit({ preventDefault() {} }); assert.equal(sent.at(-1).type, 'rename'); assert.equal(sent.at(-1).name, 'Renamed');
  get('archive').onclick(); assert.equal(sent.at(-1).type, 'archive');
  get('restore').onclick(); assert.equal(sent.at(-1).type, 'restore');
  get('new').onclick(); assert.equal(get('empty').hidden, false);
  const body = get('messages').children[0].children[1];
  assert.equal(body.children.map((item: any) => item.textContent).join(''), 'Safe code <img src=x onerror=alert(1)>');
  assert.equal(get('boundary').textContent, 'Review');
});


test('early bootstrap survives main parse failure and reports only fixed error categories', () => {
  const scripts = [...conversationHtml().matchAll(/<script nonce="[^"]+">([\s\S]*?)<\/script>/g)].map(match => match[1]);
  assert.equal(scripts.length, 2);
  const sent: any[] = [], handlers = new Map<string, (event?: any) => void>();
  let acquisitions = 0;
  const window = { addEventListener: (type: string, handler: (event?: any) => void) => handlers.set(type, handler) };
  const context = vm.createContext({window, acquireVsCodeApi: () => { acquisitions++; return { postMessage: (message: any) => sent.push(message) }; }});
  vm.runInContext(scripts[0], context);
  assert.equal(acquisitions, 1);
  assert.equal(sent[0].phase, 'bootstrap');
  assert.throws(() => vm.runInContext(scripts[1] + '\nconst = ;', context), /SyntaxError/);
  handlers.get('error')!({ target: window, message: 'private source and key' });
  handlers.get('error')!({ target: {}, message: 'private resource URL' });
  handlers.get('unhandledrejection')!({reason:'private rejection'});
  handlers.get('securitypolicyviolation')!({blockedURI:'private endpoint'});
  assert.deepEqual(sent.slice(1).map(message => message.source), ['script','resource','promise','csp']);
  assert.ok(!sent.some(message => message.phase === 'main' || message.type === 'ready'));
  assert.ok(!JSON.stringify(sent).includes('private'));
});
