#Requires -Version 5.1
# Generated by Build-CodeEkoWarmup.cjs. Edit this template, then regenerate.
[CmdletBinding()]
param(
    [string]$Endpoint,
    [string]$Model,
    [Security.SecureString]$ApiKey,
    [ValidateSet('Full access', 'Workspace', 'Review')][string]$PermissionMode = 'Full access',
    [ValidateSet('User message', 'Standard')][string]$CompatibilityMode = 'User message',
    [ValidateRange(1, 100)][int]$RequestsPerBatch = 5,
    [ValidateRange(1, 12)][int]$Batches = 3,
    [ValidateRange(0, 3600)][int]$IdleSeconds = 600,
    [ValidateRange(1, 600)][int]$TimeoutSeconds = 300,
    [switch]$NoStreaming,
    [switch]$FreshConnections,
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Net.Http
if (!$Endpoint) { $Endpoint = Read-Host 'API base URL from CodeEko settings' }
if (!$Model) { $Model = Read-Host 'Exact upstream model ID from CodeEko settings' }
$Endpoint = $Endpoint.Trim().TrimEnd('/')
$Model = $Model.Trim()
if (!$Model) { throw 'A model ID is required.' }
$address = $null
if (![Uri]::TryCreate($Endpoint, [UriKind]::Absolute, [ref]$address) -or
    $address.Scheme -ne 'https' -or $address.UserInfo -or $address.Query -or $address.Fragment) {
    throw 'Use an HTTPS API base URL without credentials, query parameters or fragments.'
}
if ($address.AbsolutePath -notmatch '/v\d+(?:(?:alpha|beta)\d*)?(?:/|$)') { $Endpoint += '/v1' }
if (!$OutputPath) { $OutputPath = Join-Path $PWD ('codeeko-warmup-' + [DateTime]::UtcNow.ToString('yyyyMMdd-HHmmss') + '-' + [Guid]::NewGuid().ToString('N').Substring(0, 6) + '.json') }
$OutputPath = [IO.Path]::GetFullPath($OutputPath)
if (Test-Path -LiteralPath $OutputPath) { throw 'The output file already exists. Choose a new OutputPath.' }
if (!(Test-Path -LiteralPath ([IO.Path]::GetDirectoryName($OutputPath)) -PathType Container)) { throw 'The output directory must already exist.' }
if (!$ApiKey) { $ApiKey = Read-Host 'API key (hidden)' -AsSecureString }

# GENERATED_REQUEST_PROFILES
$profiles = ConvertFrom-Json -InputObject $profilesJson
$requestProfile = $profiles.PSObject.Properties[$PermissionMode + '|' + $CompatibilityMode].Value
$requestObject = [ordered]@{ model = $Model; messages = @($requestProfile.messages); temperature = 0; stream = !$NoStreaming; max_tokens = 4096 }
if ($CompatibilityMode -eq 'Standard') { $requestObject.response_format = @{ type = 'json_object' } }
$RequestBody = ConvertTo-Json -InputObject $requestObject -Depth 12 -Compress

function Read-WarmupMetadata {
    param($Data, $Report)
    foreach ($name in @('prompt_tokens', 'completion_tokens', 'total_tokens')) {
        $value = $Data.usage.$name
        if (($value -is [int] -or $value -is [long] -or $value -is [double]) -and $value -ge 0 -and $value -le 1e12) { $Report.usage[$name] = $value }
    }
    foreach ($choice in $Data.choices) {
        if ($null -ne $choice.index -and $choice.index -ne 0) { continue }
        if ($null -ne $choice.finish_reason) {
            $Report.finishReason = if ($choice.finish_reason -in @('stop', 'length', 'content_filter', 'tool_calls', 'function_call', 'MALFORMED_FUNCTION_CALL')) { $choice.finish_reason } else { 'other' }
        }
    }
}

# GENERATED_PROBE_FUNCTIONS

function Get-WarmupClient {
    $handler = New-Object Net.Http.HttpClientHandler
    $handler.AllowAutoRedirect = $false
    $client = New-Object Net.Http.HttpClient($handler)
    $client.Timeout = [TimeSpan]::FromMilliseconds(-1)
    if ($FreshConnections) { $client.DefaultRequestHeaders.ConnectionClose = $true }
    return $client
}

function Get-WarmupMedian {
    param([object[]]$Values)
    $sorted = @($Values | Sort-Object)
    if (!$sorted.Count) { return $null }
    $middle = [int][Math]::Floor($sorted.Count / 2)
    if ($sorted.Count % 2) { return $sorted[$middle] }
    return [Math]::Round(($sorted[$middle - 1] + $sorted[$middle]) / 2, 3)
}

function Save-WarmupReport {
    $report.updatedAtUtc = [DateTime]::UtcNow.ToString('o')
    $report.summary = @(foreach ($batch in 1..$Batches) {
        $rows = @($results | Where-Object { $_.batch -eq $batch })
        if (!$rows.Count) { continue }
        $valid = @($rows | Where-Object { $_.validReply })
        $repeated = @($valid | Where-Object { $_.position -gt 1 })
        [PSCustomObject]@{ batch = $batch; attempted = $rows.Count; validReplies = $valid.Count
            invalidOrFailed = $rows.Count - $valid.Count; firstRequestValid = $rows[0].validReply
            firstRequestSeconds = $rows[0].totalSeconds
            repeatedValidMedianSeconds = Get-WarmupMedian @($repeated | ForEach-Object { $_.totalSeconds })
            validMedianFirstTextSeconds = Get-WarmupMedian @($valid | ForEach-Object { $_.firstTextSeconds }) }
    })
    $report.results = @($results.ToArray())
    $json = ConvertTo-Json -InputObject $report -Depth 12
    $temporary = $OutputPath + '.' + [Guid]::NewGuid().ToString('N') + '.tmp'
    try {
        [IO.File]::WriteAllText($temporary, $json, (New-Object Text.UTF8Encoding($false)))
        Move-Item -LiteralPath $temporary -Destination $OutputPath -Force
    } finally { if (Test-Path -LiteralPath $temporary) { Remove-Item -LiteralPath $temporary } }
}

$results = New-Object 'Collections.Generic.List[object]'
$report = [ordered]@{ warmupProbeVersion = 1; requestTemplateVersion = $templateVersion
    startedAtUtc = [DateTime]::UtcNow.ToString('o'); updatedAtUtc = $null; completed = $false; state = 'starting'
    transport = 'PowerShell System.Net.Http.HttpClient'; powerShellVersion = $PSVersionTable.PSVersion.ToString()
    note = 'Exact synthetic fresh-chat hello message templates; no repository context, model actions, retries or accumulated history. Idle periods make no probe requests; they do not guarantee a cold server or flushed cache. PowerShell transport differs from VS Code.'
    settings = @{ requestsPerBatch = $RequestsPerBatch; batches = $Batches; idleSeconds = $IdleSeconds; timeoutSeconds = $TimeoutSeconds
        permissionMode = $PermissionMode; compatibilityMode = $CompatibilityMode; streaming = !$NoStreaming; temperature = 0; maxOutputTokens = 4096
        connectionPolicy = $(if ($FreshConnections) { 'new-client-per-request-and-connection-close' } else { 'reuse-client-across-all-batches' }) }
    messageDigest = $requestProfile.messageDigest; promptCharacters = (@($requestProfile.messages | ForEach-Object { $_.content.Length }) | Measure-Object -Sum).Sum
    waits = @(); summary = @(); results = @()
}
$pointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($ApiKey)
try { $plainKey = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($pointer) }
finally { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($pointer) }
if ($Model -match '^(?:models/)?[a-zA-Z0-9][a-zA-Z0-9._-]{0,149}$' -and (!$plainKey -or !$Model.Contains($plainKey))) { $report.model = $Model }
$sharedClient = $null
try {
    Save-WarmupReport
    Write-Output ('Report: ' + $OutputPath)
    if (!$FreshConnections) { $sharedClient = Get-WarmupClient }
    for ($batch = 1; $batch -le $Batches; $batch++) {
        if ($batch -gt 1 -and $IdleSeconds -gt 0) {
            $report.state = 'waiting'; Save-WarmupReport
            Write-Output ('Waiting {0} seconds before batch {1}/{2}...' -f $IdleSeconds, $batch, $Batches)
            $idleStart = [DateTime]::UtcNow.ToString('o')
            $idleWatch = [Diagnostics.Stopwatch]::StartNew()
            while ($idleWatch.Elapsed.TotalSeconds -lt $IdleSeconds) {
                Write-Progress -Activity 'CodeEko API warm-up test' -Status ('Idle: {0} seconds remaining' -f [Math]::Ceiling($IdleSeconds - $idleWatch.Elapsed.TotalSeconds))
                Start-Sleep -Milliseconds 250
            }
            $report.waits += [PSCustomObject]@{ beforeBatch = $batch; startedAtUtc = $idleStart; elapsedSeconds = [Math]::Round($idleWatch.Elapsed.TotalSeconds, 3) }
        }
        for ($position = 1; $position -le $RequestsPerBatch; $position++) {
            $report.state = 'requesting'; Save-WarmupReport
            Write-Output ('Batch {0}/{1}, request {2}/{3}' -f $batch, $Batches, $position, $RequestsPerBatch)
            $requestClient = if ($FreshConnections) { Get-WarmupClient } else { $sharedClient }
            try { $result = Invoke-WarmupRequest (!$NoStreaming) $plainKey $requestClient }
            finally { if ($FreshConnections -and $requestClient) { $requestClient.Dispose() } }
            $result | Add-Member -NotePropertyName batch -NotePropertyValue $batch
            $result | Add-Member -NotePropertyName position -NotePropertyValue $position
            $valid = $result.expectedAction -and $result.finishReason -eq 'stop' -and $result.outcome -in @('stream-ended', 'response-received', 'non-stream-response')
            $result | Add-Member -NotePropertyName validReply -NotePropertyValue ([bool]$valid)
            [void]$results.Add($result)
            Save-WarmupReport
            Write-Output ('  {0}s; valid reply: {1}; outcome: {2}' -f $result.totalSeconds, $result.validReply, $result.outcome)
        }
    }
    $report.completed = $true; $report.state = 'complete'; Save-WarmupReport
    Write-Output ('Finished. Send this JSON report: ' + $OutputPath)
} finally {
    if ($sharedClient) { $sharedClient.Dispose() }
    $plainKey = $null
    Write-Progress -Activity 'CodeEko API warm-up test' -Completed
    # Per-request checkpoints survive Ctrl+C or process termination.
}
