import { randomBytes } from 'node:crypto';

export function conversationHtml(): string {
  const nonce = randomBytes(16).toString('hex');
  return String.raw`<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}'"><meta name="viewport" content="width=device-width, initial-scale=1">
<style nonce="${nonce}">
*{box-sizing:border-box}body{margin:0;color:var(--vscode-foreground);background:var(--vscode-editor-background);font:var(--vscode-font-size)/1.6 var(--vscode-font-family);height:100vh;display:flex;flex-direction:column}
button,select,textarea{font:inherit;color:inherit}button{cursor:pointer;border:1px solid transparent;border-radius:6px;padding:5px 10px;background:transparent}button:hover{background:var(--vscode-toolbar-hoverBackground)}button:disabled{opacity:.4;cursor:default}button:focus-visible,select:focus-visible,textarea:focus-visible,summary:focus-visible{outline:1px solid var(--vscode-focusBorder);outline-offset:2px}[hidden]{display:none!important}
header{padding:12px 16px;border-bottom:1px solid var(--vscode-panel-border);display:flex;align-items:center;gap:8px}select{min-width:0;flex:1;background:var(--vscode-dropdown-background);border:1px solid var(--vscode-dropdown-border);border-radius:6px;padding:5px 8px}details{position:relative}summary{cursor:pointer;padding:4px 8px;list-style:none}.menu{position:absolute;right:0;top:32px;z-index:2;width:190px;padding:6px;background:var(--vscode-menu-background,var(--vscode-editor-background));border:1px solid var(--vscode-panel-border);border-radius:8px;box-shadow:0 4px 16px #0003}.menu button{display:block;width:100%;text-align:left}
#timeline{flex:1;min-height:0;overflow:auto;padding:24px 20px}#messages,#empty{max-width:780px;margin:auto}article{margin-bottom:28px;overflow-wrap:anywhere}.role{font-size:11px;font-weight:600;color:var(--vscode-descriptionForeground);margin-bottom:7px}.content{white-space:pre-wrap}.user{margin-left:12%;padding:12px 16px;background:var(--vscode-textBlockQuote-background,var(--vscode-input-background));border:1px solid var(--vscode-panel-border);border-radius:14px}.assistant{padding:0 2px}.content code{font-family:var(--vscode-editor-font-family);background:var(--vscode-textCodeBlock-background);padding:1px 4px;border-radius:4px}#empty{padding-top:clamp(20px,10vh,90px)}h1{font-size:24px;line-height:1.25;font-weight:600;letter-spacing:-.5px;margin:0 0 12px}#empty p{color:var(--vscode-descriptionForeground);margin:0 0 24px}.suggestion{display:block;text-align:left;border-color:var(--vscode-panel-border);margin:8px 0;padding:10px 14px;width:100%;max-width:420px}
footer{flex:none;padding:8px 16px 14px;max-height:50vh;overflow:auto}.compose-wrap{max-width:780px;margin:auto}.status-line{display:flex;gap:8px;align-items:baseline;min-height:28px;color:var(--vscode-descriptionForeground);font-size:12px}#status{overflow-wrap:anywhere;flex:1}.working{color:var(--vscode-progressBar-background)}#latest{font-size:11px}#composer{border:1px solid var(--vscode-input-border,var(--vscode-panel-border));border-radius:12px;background:var(--vscode-input-background);padding:10px 12px}#composer:focus-within{border-color:var(--vscode-focusBorder)}textarea{display:block;width:100%;min-height:48px;max-height:180px;resize:none;background:transparent;border:0;outline:none!important;padding:0;line-height:1.5;color:var(--vscode-input-foreground)}textarea::placeholder{color:var(--vscode-input-placeholderForeground)}.compose-tools{display:flex;align-items:center;gap:8px;margin-top:8px}.context{flex:1;min-width:0;font-size:11px;color:var(--vscode-descriptionForeground)}#boundary,#model{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}#send{background:var(--vscode-button-background);color:var(--vscode-button-foreground);font-weight:600}#send:hover{background:var(--vscode-button-hoverBackground)}#cancel{border-color:var(--vscode-button-secondaryBackground);background:var(--vscode-button-secondaryBackground);color:var(--vscode-button-secondaryForeground)}.hint{font-size:11px;color:var(--vscode-descriptionForeground);margin:5px 2px 0}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0)}@media(max-width:360px){header{padding:8px}#timeline{padding:16px 12px}footer{padding:8px}.user{margin-left:4%}.hint{font-size:10px}}
#home{min-width:0;max-width:55%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}header>button:not(#home),header>details{flex-shrink:0}.menu hr{border:0;border-top:1px solid var(--vscode-panel-border)}#archivedChats{font-size:12px;color:var(--vscode-descriptionForeground)}header{border-bottom:0;padding:8px 12px}.spacer{flex:1}#home,#history,#settings,#new{color:var(--vscode-descriptionForeground)}#history,#settings,#new{font-size:18px;padding:4px 8px}#timeline{padding:0 16px 16px}#empty{padding:0}#chats button{display:block;width:100%;text-align:left;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;padding:6px 4px}#viewAll{font-size:12px;color:var(--vscode-descriptionForeground);padding:4px}#noChats{font-size:12px;margin:8px 4px}.welcome{text-align:center;margin-top:70px;font:32px monospace;color:var(--vscode-disabledForeground);opacity:.5}#messages{padding-top:20px}#composer{border-radius:18px;padding:14px}textarea{min-height:66px}.compose-tools{gap:4px}#boundary{font-size:10px;max-width:100px;color:var(--vscode-descriptionForeground)}#model{max-width:55%;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:11px;color:var(--vscode-descriptionForeground);padding:5px}#send,#cancel{border-radius:50%;width:30px;height:30px;padding:0;font-size:18px;flex:none}.hint{margin-top:8px}#repository{overflow-wrap:anywhere}
#renameDialog,#choiceDialog{color:var(--vscode-foreground);background:var(--vscode-editor-background);border:1px solid var(--vscode-panel-border);border-radius:16px;padding:20px;width:calc(100% - 32px);max-width:440px;margin:auto auto 32px;box-shadow:0 12px 40px #0005}#renameDialog::backdrop,#choiceDialog::backdrop{background:#0009}#renameDialog h2,#choiceDialog h2{font-size:14px;margin:0 0 8px}#renameDialog p{font-size:12px;color:var(--vscode-descriptionForeground);margin:0 0 12px}#renameClose{position:absolute;right:12px;top:10px}#renameInput{width:100%;font:inherit;background:var(--vscode-input-background);color:var(--vscode-input-foreground);border:1px solid var(--vscode-input-border,var(--vscode-panel-border));border-radius:6px;padding:8px;outline-color:var(--vscode-focusBorder)}.renameButtons{display:flex;justify-content:flex-end;gap:8px;margin-top:12px}#renameCancel{border-color:var(--vscode-panel-border)}#renameSave{background:var(--vscode-button-background);color:var(--vscode-button-foreground)}#choiceDialog{max-height:calc(100vh - 48px);overflow:auto}#choiceTitle{overflow-wrap:anywhere}#choiceItems{display:flex;flex-direction:column;gap:8px;margin:16px 0}#choiceItems button{text-align:left;white-space:normal;overflow-wrap:anywhere;border:1px solid var(--vscode-panel-border);padding:10px}#choiceCancel{float:right;border:1px solid var(--vscode-panel-border)}#renameError{color:var(--vscode-errorForeground)!important;margin-top:8px!important}
#permissionMenu{margin:0;padding:12px;width:360px;max-width:calc(100vw - 24px);border:1px solid var(--vscode-panel-border);border-radius:14px;background:var(--vscode-editor-background);color:var(--vscode-foreground);box-shadow:0 8px 30px #0005;overflow:auto}#permissionMenu h2{font-size:12px;font-weight:400;color:var(--vscode-descriptionForeground);margin:0 4px 8px}#permissionMenu button{position:relative;display:block;text-align:left;width:100%;padding:8px 30px 8px 8px;line-height:1.35}#permissionMenu small{display:block;font-size:11px;color:var(--vscode-descriptionForeground)}#permissionMenu [aria-checked="true"]::after{content:'✓';position:absolute;right:8px;top:12px}#permissionMenu [aria-checked="true"]{color:var(--vscode-textLink-foreground)}#permissionMenu #permissionFull[aria-checked="true"]{color:var(--vscode-editorWarning-foreground)}#permissionMenu p{font-size:10px;color:var(--vscode-descriptionForeground);margin:8px 4px 0}
#historyTools{padding:10px 0;border-bottom:1px solid var(--vscode-panel-border);margin-bottom:6px}#historySearch{width:100%;font:inherit;background:var(--vscode-input-background);color:var(--vscode-input-foreground);border:1px solid var(--vscode-panel-border);border-radius:8px;padding:8px;margin-bottom:8px}#historyFilter{font-size:12px;max-width:65%;border:0;background:transparent;color:var(--vscode-descriptionForeground)}.historyAge{float:right;font-size:10px;color:var(--vscode-descriptionForeground);padding-top:8px}#chats button{display:flex;gap:12px;align-items:center}.chatName{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis}.chatAge{flex:none;font-size:11px;color:var(--vscode-descriptionForeground)}#empty:has(#historyTools:not([hidden])){border:1px solid var(--vscode-panel-border);border-radius:12px;padding:0 10px 10px}.welcome{display:none}
#modelMenu{margin:0;padding:12px;width:300px;max-width:calc(100vw - 24px);border:1px solid var(--vscode-panel-border);border-radius:14px;background:var(--vscode-editor-background);color:var(--vscode-foreground);box-shadow:0 8px 30px #0005;overflow:auto}#modelMenu h2{font-size:12px;color:var(--vscode-descriptionForeground);font-weight:400;margin:0 4px 8px}#modelItems button{display:block;width:100%;text-align:left;position:relative;padding:7px 28px 7px 6px;overflow-wrap:anywhere}#modelItems [aria-checked="true"]::after{content:'✓';position:absolute;right:6px}#modelSearch,#manualModel{font:inherit;width:100%;background:var(--vscode-input-background);color:var(--vscode-input-foreground);border:1px solid var(--vscode-panel-border);border-radius:6px;padding:6px;margin-bottom:8px}#modelStatus{font-size:11px;color:var(--vscode-descriptionForeground)}
</style></head><body>
<header><button id="home" title="Chat history">Chats</button><span class="spacer"></span><button id="history" title="Show all chats" aria-label="Chat history"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M3 10a9 9 0 1 1 2 8M3 4v6h6m3-4v6l4 2"/></svg></button><button id="settings" title="Settings" aria-label="Settings"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path stroke-linejoin="round" d="M9.15 4.95 L9.98 2.51 L14.02 2.51 L14.85 4.95 L16.68 6.01 L19.21 5.51 L21.23 9.00 L19.53 10.94 L19.53 13.06 L21.23 15.00 L19.21 18.49 L16.68 17.99 L14.85 19.05 L14.02 21.49 L9.98 21.49 L9.15 19.05 L7.32 17.99 L4.79 18.49 L2.77 15.00 L4.47 13.06 L4.47 10.94 L2.77 9.00 L4.79 5.51 L7.32 6.01Z"/><circle cx="12" cy="12" r="2.75"/></svg></button><button id="new" title="New chat" aria-label="New chat"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M12 4H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-7M17 3l4 4-10 10-5 1 1-5Z"/></svg></button><details id="actions"><summary aria-label="Task actions">•••</summary><div class="menu"><button id="rename">Rename</button><button id="archive">Archive</button><button id="restore" hidden>Restore chat</button></div></details></header>
<main id="timeline" aria-label="Conversation history"><section id="empty"><div id="historyTools" hidden><label class="sr-only" for="historySearch">Search chats</label><input id="historySearch" placeholder="Search chats" type="search"><label class="sr-only" for="historyFilter">Chat filter</label><select id="historyFilter"><option value="all">All chats</option><option value="active">Active chats</option><option value="archived">Archived chats</option></select><span class="historyAge">Last activity</span></div><nav id="chats" aria-label="Previous chats"></nav><button id="viewAll">View all</button><p id="noChats">Your chats will appear here.</p><div class="welcome" aria-hidden="true">❯_</div></section><div id="messages" role="log" aria-live="polite" aria-relevant="additions"></div></main>
<footer><div class="compose-wrap"><div class="status-line"><span id="status" role="status"></span><button id="latest" hidden>Jump to latest ↓</button></div><div id="composer"><label for="input" class="sr-only">Message</label><textarea id="input" rows="3" maxlength="8000" placeholder="Ask anything about this repository…"></textarea><div class="compose-tools"><button id="permissions" title="Change permissions" aria-label="Change permissions"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M12 3 5 6v6c0 4 7 9 7 9s7-5 7-9V6Z"/><path d="M12 8v5m0 3h.01"/></svg></button><span id="boundary" class="sr-only"></span><span class="spacer"></span><button id="model" title="Select model">Select model ⌄</button><button id="send" title="Send message (Enter)" aria-label="Send message" disabled>↑</button><button id="cancel" title="Stop task" hidden>■</button></div></div><p class="hint"><span id="repository"></span> · Shift+Enter for newline</p></div></footer>
<section id="modelMenu" popover="auto" aria-labelledby="modelTitle"><h2 id="modelTitle">Select model</h2><label class="sr-only" for="modelSearch">Search models</label><input id="modelSearch" type="search" placeholder="Search models"><p id="modelStatus" role="status"></p><div id="modelItems" role="menu" aria-label="Available models"></div><form id="manualModelForm" hidden><label for="manualModel">Model ID</label><input id="manualModel" maxlength="200" required><button type="submit">Use model ID</button></form></section>
<section id="permissionMenu" popover="auto" aria-labelledby="permissionTitle"><h2 id="permissionTitle">How should repository actions be allowed?</h2><div role="menu" aria-label="Permission mode"><button id="permissionReview" role="menuitemradio" aria-checked="false">Review<small>Read and explain code. No repository edits.</small></button><button id="permissionWorkspace" role="menuitemradio" aria-checked="false">Workspace<small>Repository edits and validation; confirm destructive edits and local commits.</small></button><button id="permissionFull" role="menuitemradio" aria-checked="false">Full access<small>Repository edits, validation and requested local commits without confirmations.</small></button></div><p>Workspace asks before destructive edits; Full access proceeds automatically. General shell commands are unavailable in every mode.</p></section>
<dialog id="renameDialog" aria-labelledby="renameTitle" aria-describedby="renameDescription"><form id="renameForm"><button id="renameClose" type="button" aria-label="Close rename dialog">×</button><h2 id="renameTitle">Rename chat</h2><p id="renameDescription">Keep it short and recognizable.</p><label class="sr-only" for="renameInput">Chat name</label><input id="renameInput" maxlength="100" autocomplete="off" required><p id="renameError" role="alert" hidden></p><div class="renameButtons"><button id="renameCancel" type="button">Cancel</button><button id="renameSave" type="submit">Save</button></div></form></dialog>
<dialog id="choiceDialog" aria-labelledby="choiceTitle"><h2 id="choiceTitle"></h2><div id="choiceItems"></div><button id="choiceCancel">Cancel</button></dialog>
<script nonce="${nonce}">
const vscode=acquireVsCodeApi(),el=id=>document.getElementById(id);
let questionId='',busy=false,threadId='',rendered='',drafts=new Map(),home=true,showAll=false,lastState,switchPending=false;
const resize=()=>{el('input').style.height='auto';el('input').style.height=Math.min(el('input').scrollHeight,180)+'px';};
const refresh=()=>{el('send').disabled=(busy&&!questionId)||(!home&&lastState?.thread.archived)||!threadId||!el('input').value.trim();el('send').hidden=busy&&!questionId;el('cancel').hidden=!busy;el('cancel').disabled=!busy;};
const bottom=()=>{el('timeline').scrollTop=el('timeline').scrollHeight;el('latest').hidden=true;};
const nearBottom=()=>el('timeline').scrollHeight-el('timeline').scrollTop-el('timeline').clientHeight<70;
el('timeline').onscroll=()=>{el('latest').hidden=nearBottom();};el('latest').onclick=bottom;
el('input').oninput=()=>{drafts.set(home?'home':threadId,el('input').value);resize();refresh();};
el('send').onclick=()=>{if((busy&&!questionId)||(!home&&lastState?.thread.archived)||!threadId||!el('input').value.trim())return;const text=el('input').value;if(questionId){const id=questionId;questionId='';el('input').value='';drafts.delete(threadId);resize();refresh();vscode.postMessage({type:'answer',id,text});return;}busy=true;refresh();switchPending=home;vscode.postMessage({type:'send',text,newConversation:home});drafts.delete(home?'home':threadId);home=false;el('input').value='';drafts.delete(threadId);resize();el('status').textContent='Starting…';bottom();};
el('input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&e.keyCode!==229){e.preventDefault();el('send').onclick();}};
el('cancel').onclick=()=>{vscode.postMessage({type:'cancel'});el('cancel').disabled=true;el('status').textContent='Stopping…';};
function goHome(all=false){if(busy)return;drafts.set(home?'home':threadId,el('input').value);home=true;showAll=all;el('historyFilter').value='all';el('historySearch').value='';el('input').value=drafts.get('home')||'';rendered='';if(lastState)renderState(lastState);resize();el('input').focus();}
el('historySearch').oninput=()=>{if(lastState)renderState(lastState);};el('historyFilter').onchange=()=>{if(lastState)renderState(lastState);};el('new').onclick=()=>goHome();el('home').onclick=()=>goHome();el('history').onclick=()=>goHome(true);el('viewAll').onclick=()=>goHome(!showAll);el('settings').onclick=()=>vscode.postMessage({type:'settings'});const permissionChoices=[['permissionReview','Review'],['permissionWorkspace','Workspace'],['permissionFull','Full access']];
el('permissions').setAttribute('aria-haspopup','menu');
el('permissions').onclick=()=>{if(busy)return;const rect=el('permissions').getBoundingClientRect();el('permissionMenu').style.left=Math.max(12,Math.min(rect.left,window.innerWidth-372))+'px';el('permissionMenu').style.top='auto';el('permissionMenu').style.bottom=Math.max(12,window.innerHeight-rect.top+8)+'px';el('permissionMenu').style.maxHeight=Math.max(100,rect.top-20)+'px';el('permissionMenu').togglePopover();if(el('permissionMenu').matches(':popover-open'))el(permissionChoices.find(([,mode])=>mode===lastState?.mode)?.[0]||'permissionReview').focus();};
for(const [id,mode] of permissionChoices)el(id).onclick=()=>{if(busy)return;el('permissionMenu').hidePopover();el('permissions').focus();vscode.postMessage({type:'permissions',mode});};
el('permissionMenu').onkeydown=e=>{const index=permissionChoices.findIndex(([id])=>el(id)===document.activeElement);let next;if(e.key==='ArrowDown')next=(index+1)%4;if(e.key==='ArrowUp')next=(index+3)%4;if(e.key==='Home')next=0;if(e.key==='End')next=3;if(next!==undefined){e.preventDefault();el(permissionChoices[next][0]).focus();}};
let availableModels=[];
function renderModels(){el('modelItems').replaceChildren();for(const model of availableModels.filter(id=>id.toLowerCase().includes(el('modelSearch').value.toLowerCase()))){const row=document.createElement('button');row.textContent=model;row.setAttribute('role','menuitemradio');row.setAttribute('aria-checked',String(model===lastState?.model));row.onclick=()=>{if(!busy)vscode.postMessage({type:'chooseModel',model});};el('modelItems').append(row);}}
el('model').setAttribute('aria-haspopup','menu');el('modelSearch').oninput=renderModels;
el('model').onclick=()=>{if(busy)return;const rect=el('model').getBoundingClientRect();el('modelMenu').style.left=Math.max(12,Math.min(rect.left,window.innerWidth-312))+'px';el('modelMenu').style.top='auto';el('modelMenu').style.bottom=Math.max(12,window.innerHeight-rect.top+8)+'px';el('modelMenu').style.maxHeight=Math.max(100,rect.top-20)+'px';el('modelMenu').togglePopover();if(!el('modelMenu').matches(':popover-open'))return;availableModels=[];el('modelSearch').value='';renderModels();el('manualModelForm').hidden=true;el('modelStatus').textContent='Loading models…';el('modelSearch').focus();vscode.postMessage({type:'selectModel'});};
el('manualModelForm').onsubmit=e=>{e.preventDefault();if(!busy&&el('manualModel').value.trim())vscode.postMessage({type:'chooseModel',model:el('manualModel').value.trim(),manual:true});};
el('modelMenu').onkeydown=e=>{const rows=Array.from(el('modelItems').children);const index=rows.indexOf(document.activeElement);let next;if(e.key==='ArrowDown')next=(index+1)%rows.length;if(e.key==='ArrowUp')next=(index+rows.length-1)%rows.length;if(next!==undefined&&rows.length){e.preventDefault();rows[next].focus();}};

for(const [id,type] of [['archive','archive'],['restore','restore']])el(id).onclick=()=>{el('actions').open=false;vscode.postMessage({type});};
let renameId='',renamePending=false;
function closeRename(){el('renameDialog').close();el('actions').querySelector('summary').focus();}
el('rename').onclick=()=>{if(busy||!lastState)return;el('actions').open=false;renameId=threadId;renamePending=false;el('renameInput').value=lastState.thread.name;el('renameError').hidden=true;el('renameSave').disabled=false;el('renameDialog').showModal();el('renameInput').focus();el('renameInput').select();};
el('renameDialog').oncancel=e=>{e.preventDefault();closeRename();};el('renameClose').onclick=closeRename;el('renameCancel').onclick=closeRename;
el('renameInput').oninput=()=>{el('renameSave').disabled=renamePending||!el('renameInput').value.trim();};
el('renameForm').onsubmit=e=>{e.preventDefault();const name=el('renameInput').value.trim();if(renamePending||!name||name.length>100)return;renamePending=true;el('renameSave').disabled=true;el('renameError').hidden=true;vscode.postMessage({type:'rename',id:renameId,name});};
// Render a small safe inline subset. All model/repository text stays in text nodes.
function content(node,text){for(const part of text.split(/(\x60[^\x60\n]+\x60|\*\*[^*\n]+\*\*)/g)){const code=part.startsWith('\x60')&&part.endsWith('\x60');const bold=part.startsWith('**')&&part.endsWith('**');const span=document.createElement(code?'code':bold?'strong':'span');span.textContent=code?part.slice(1,-1):bold?part.slice(2,-2):part;node.append(span);}}
let choiceId='';
function replyChoice(index){const id=choiceId;choiceId='';el('choiceDialog').close();vscode.postMessage({type:'choiceReply',id,index});}
el('choiceCancel').onclick=()=>replyChoice(null);el('choiceDialog').oncancel=e=>{e.preventDefault();replyChoice(null);};
function renderState(m){if(m.type==='choice'){choiceId=m.id;el('choiceTitle').textContent=m.question;el('choiceItems').replaceChildren();m.choices.forEach((text,index)=>{const button=document.createElement('button');button.textContent=text;button.onclick=()=>replyChoice(index);el('choiceItems').append(button);});if(!el('choiceDialog').open)el('choiceDialog').showModal();el('choiceCancel').focus();return;}if(m.type==='choiceClosed'){if(choiceId===m.id){choiceId='';el('choiceDialog').close();}return;}if(m.type==='models'){availableModels=m.items;el('modelStatus').textContent=m.error||(m.items.length?'':'No models returned.');el('manualModelForm').hidden=!m.error;renderModels();return;}if(m.type==='modelChosen'){el('modelMenu').hidePopover();el('model').focus();return;}if(m.type==='renameResult'){if(m.id!==renameId)return;renamePending=false;el('renameSave').disabled=!el('renameInput').value.trim();if(m.ok)closeRename();else{el('renameError').textContent=m.error;el('renameError').hidden=false;}return;}if(m.type==='home'){busy=false;goHome();return;}if(m.type==='progress'){el('status').textContent=m.text;return;}if(m.type!=='state')return;lastState=m;questionId=m.questionId||'';
const switched=threadId!==m.thread.id,wasBusy=busy,follow=switched||nearBottom();
if(switched||switchPending){if(threadId&&!switchPending)drafts.set(home?'home':threadId,el('input').value);threadId=m.thread.id;el('input').value=drafts.get(home?'home':threadId)||'';switchPending=false;resize();}
busy=m.busy;for(const [id,mode] of permissionChoices){el(id).setAttribute('aria-checked',String(m.mode===mode));el(id).disabled=busy;}if(busy)el('permissionMenu').hidePopover();el('boundary').textContent=m.mode;el('permissions').title='Change permissions · '+m.mode;el('permissions').setAttribute('aria-label','Change permissions, current mode: '+m.mode);el('permissions').style.color=m.mode==='Full access'?'var(--vscode-editorWarning-foreground)':'';el('boundary').title=m.mode+' · '+(['Workspace','Full access'].includes(m.mode)?'Editing enabled':'Read-only');el('model').textContent=(m.model||'Select model')+' ⌄';el('repository').textContent='⌘ '+(m.root.split(/[\\/]/).pop()||m.root)+' · '+m.mode;el('repository').title=m.root;
el('chats').replaceChildren();el('historyTools').hidden=!showAll;const filter=showAll?el('historyFilter').value:'active';const query=showAll?el('historySearch').value.toLowerCase().trim():'';
const chats=[...m.threads].reverse().filter(t=>(filter==='all'||(t.archived===true)===(filter==='archived'))&&t.name.toLowerCase().includes(query)).sort((a,b)=>(Date.parse(b.lastUsedAt)||0)-(Date.parse(a.lastUsedAt)||0));
for(const t of (showAll?chats:chats.slice(0,3))){const row=document.createElement('button');const name=document.createElement('span');name.className='chatName';name.textContent=t.name+(t.archived?' · Archived':'');const age=document.createElement('span');age.className='chatAge';const date=Date.parse(t.lastUsedAt),minutes=Math.max(0,Math.floor((Date.now()-date)/60000));age.textContent=!Number.isFinite(date)?'—':minutes<1?'now':minutes<60?minutes+'m':minutes<1440?Math.floor(minutes/60)+'h':Math.floor(minutes/1440)+'d';age.title=Number.isFinite(date)?new Date(date).toLocaleString():'Activity time unavailable for this older chat';row.append(name,age);row.title=t.name;row.disabled=busy;row.onclick=()=>{if(busy)return;drafts.set(home?'home':threadId,el('input').value);home=false;switchPending=true;rendered='';vscode.postMessage({type:'switch',id:t.id});};el('chats').append(row);}el('viewAll').hidden=showAll||chats.length<=3;el('viewAll').textContent='View all ('+m.threads.length+')';el('noChats').hidden=chats.length>0;el('noChats').textContent=query?'No matching chats.':'No chats to show.';
el('home').textContent=home?'Chats':'← '+m.thread.name;el('home').title=home?'Chat history':m.thread.name;el('archive').hidden=m.thread.archived===true;el('restore').hidden=m.thread.archived!==true;el('empty').hidden=!home;el('messages').hidden=home;el('actions').hidden=home;el('input').placeholder=questionId?'Reply to the agent…':home?'Ask anything about this repository…':'Send a follow-up…';
const signature=JSON.stringify([threadId,m.thread.messages]);if(signature!==rendered){rendered=signature;el('messages').replaceChildren();for(const msg of m.thread.messages){const a=document.createElement('article');a.className=msg.role==='user'?'user':'assistant';const role=document.createElement('div');role.className='role';role.textContent=msg.role==='user'?'You':'Agent';const body=document.createElement('div');body.className='content';content(body,msg.content);a.append(role,body);el('messages').append(a);}if(follow)bottom();else el('latest').hidden=false;}
for(const id of ['rename','archive','restore','new','home','history','settings','model','permissions','viewAll'])el(id).disabled=busy;el('status').className=busy?'working':'';
if(!busy)el('status').textContent=home?'':({complete:'Completed',cancelled:'Stopped',blocked:'Needs attention',failed:'Task failed',idle:'Ready'})[m.thread.status]||'Ready';else if(!wasBusy)el('status').textContent='Working…';if(questionId)el('status').textContent='Waiting for your reply';refresh();
}window.addEventListener('message',event=>{try{renderState(event.data);if(event.data?.type==='state'&&typeof event.data.startupToken==='string')vscode.postMessage({type:'startupAck',token:event.data.startupToken});}catch{vscode.postMessage({type:'startupError',source:'script'});}});window.addEventListener('error',()=>vscode.postMessage({type:'startupError',source:'script'}));window.addEventListener('unhandledrejection',()=>vscode.postMessage({type:'startupError',source:'promise'}));vscode.postMessage({type:'ready'});
</script></body></html>`;
}
