import { randomBytes } from 'node:crypto';

export function conversationHtml(): string {
  const nonce = randomBytes(16).toString('hex');
  return String.raw`<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}'"><meta name="viewport" content="width=device-width, initial-scale=1">
<style nonce="${nonce}">
*{box-sizing:border-box}body{margin:0;color:var(--vscode-foreground);background:var(--vscode-editor-background);font:var(--vscode-font-size)/1.6 var(--vscode-font-family);height:100vh;display:flex;flex-direction:column}
button,select,textarea{font:inherit;color:inherit}button{cursor:pointer;border:1px solid transparent;border-radius:6px;padding:5px 10px;background:transparent}button:hover{background:var(--vscode-toolbar-hoverBackground)}button:disabled{opacity:.4;cursor:default}button:focus-visible,select:focus-visible,textarea:focus-visible,summary:focus-visible{outline:1px solid var(--vscode-focusBorder);outline-offset:2px}[hidden]{display:none!important}
header{padding:12px 16px;border-bottom:1px solid var(--vscode-panel-border);display:flex;align-items:center;gap:8px}select{min-width:0;flex:1;background:var(--vscode-dropdown-background);border:1px solid var(--vscode-dropdown-border);border-radius:6px;padding:5px 8px}details{position:relative}summary{cursor:pointer;padding:4px 8px;list-style:none}.menu{position:absolute;right:0;top:32px;z-index:2;width:190px;padding:6px;background:var(--vscode-menu-background,var(--vscode-editor-background));border:1px solid var(--vscode-panel-border);border-radius:8px;box-shadow:0 4px 16px #0003}.menu button{display:block;width:100%;text-align:left}
#timeline{flex:1;min-height:0;overflow:auto;padding:24px 20px}#messages,#empty{max-width:780px;margin:auto}article{margin-bottom:28px;overflow-wrap:anywhere}.role{font-size:11px;font-weight:600;color:var(--vscode-descriptionForeground);margin-bottom:7px}.content{white-space:pre-wrap}.user{margin-left:12%;padding:12px 16px;background:var(--vscode-textBlockQuote-background,var(--vscode-input-background));border:1px solid var(--vscode-panel-border);border-radius:14px}.assistant{padding:0 2px}.content code{font-family:var(--vscode-editor-font-family);background:var(--vscode-textCodeBlock-background);padding:1px 4px;border-radius:4px}#empty{padding-top:clamp(20px,10vh,90px)}h1{font-size:24px;line-height:1.25;font-weight:600;letter-spacing:-.5px;margin:0 0 12px}#empty p{color:var(--vscode-descriptionForeground);margin:0 0 24px}.suggestion{display:block;text-align:left;border-color:var(--vscode-panel-border);margin:8px 0;padding:10px 14px;width:100%;max-width:420px}
footer{flex:none;padding:8px 16px 14px;max-height:50vh;overflow:auto}.compose-wrap{max-width:780px;margin:auto}.status-line{display:flex;gap:8px;align-items:baseline;min-height:28px;color:var(--vscode-descriptionForeground);font-size:12px}#status{overflow-wrap:anywhere;flex:1}.working{color:var(--vscode-progressBar-background)}#latest{font-size:11px}#composer{border:1px solid var(--vscode-input-border,var(--vscode-panel-border));border-radius:12px;background:var(--vscode-input-background);padding:10px 12px}#composer:focus-within{border-color:var(--vscode-focusBorder)}textarea{display:block;width:100%;min-height:48px;max-height:180px;resize:none;background:transparent;border:0;outline:none!important;padding:0;line-height:1.5;color:var(--vscode-input-foreground)}textarea::placeholder{color:var(--vscode-input-placeholderForeground)}.compose-tools{display:flex;align-items:center;gap:8px;margin-top:8px}.context{flex:1;min-width:0;font-size:11px;color:var(--vscode-descriptionForeground)}#boundary,#model{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}#send{background:var(--vscode-button-background);color:var(--vscode-button-foreground);font-weight:600}#send:hover{background:var(--vscode-button-hoverBackground)}#cancel{border-color:var(--vscode-button-secondaryBackground);background:var(--vscode-button-secondaryBackground);color:var(--vscode-button-secondaryForeground)}.hint{font-size:11px;color:var(--vscode-descriptionForeground);margin:5px 2px 0}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0)}@media(max-width:360px){header{padding:8px}#timeline{padding:16px 12px}footer{padding:8px}.user{margin-left:4%}.hint{font-size:10px}}
</style></head><body>
<header><label for="threads" class="sr-only">Conversation</label><select id="threads"></select><button id="new" title="New conversation" aria-label="New conversation">＋ New</button><details id="actions"><summary aria-label="Conversation actions" title="Conversation actions">•••</summary><div class="menu"><button id="review">Review task changes</button><button id="undo">Undo task changes</button><button id="sourceControl">Source Control</button></div></details></header>
<main id="timeline" aria-label="Conversation history"><section id="empty"><h1>What would you like to work on?</h1><p>Ask about your repository, make a focused change, or work through a failing test.</p><button class="suggestion" id="explain">Explain how this repository works</button><button class="suggestion" id="repair">Investigate a failing test</button></section><div id="messages" role="log" aria-live="polite" aria-relevant="additions"></div></main>
<footer><div class="compose-wrap"><div class="status-line"><span id="status" role="status">Ready</span><button id="latest" hidden>Jump to latest ↓</button></div><div id="composer"><label for="input" class="sr-only">Message</label><textarea id="input" rows="2" maxlength="8000" placeholder="Ask about or change this repository…"></textarea><div class="compose-tools"><div class="context"><span id="boundary"></span><span id="model"></span></div><button id="send" title="Send message (Enter)" disabled>Send ↑</button><button id="cancel" hidden>Stop</button></div></div><p class="hint">Enter to send · Shift+Enter for a new line</p></div></footer>
<script nonce="${nonce}">
const vscode=acquireVsCodeApi(),el=id=>document.getElementById(id);
let busy=false,threadId='',rendered='',drafts=new Map();
const resize=()=>{el('input').style.height='auto';el('input').style.height=Math.min(el('input').scrollHeight,180)+'px';};
const refresh=()=>{el('send').disabled=busy||!threadId||!el('input').value.trim();el('send').hidden=busy;el('cancel').hidden=!busy;el('cancel').disabled=!busy;};
const bottom=()=>{el('timeline').scrollTop=el('timeline').scrollHeight;el('latest').hidden=true;};
const nearBottom=()=>el('timeline').scrollHeight-el('timeline').scrollTop-el('timeline').clientHeight<70;
el('timeline').onscroll=()=>{el('latest').hidden=nearBottom();};el('latest').onclick=bottom;
el('input').oninput=()=>{drafts.set(threadId,el('input').value);resize();refresh();};
el('send').onclick=()=>{if(busy||!threadId||!el('input').value.trim())return;const text=el('input').value;busy=true;refresh();vscode.postMessage({type:'send',text});el('input').value='';drafts.delete(threadId);resize();el('status').textContent='Starting…';bottom();};
el('input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&e.keyCode!==229){e.preventDefault();el('send').onclick();}};
el('cancel').onclick=()=>{vscode.postMessage({type:'cancel'});el('cancel').disabled=true;el('status').textContent='Stopping…';};
el('new').onclick=()=>vscode.postMessage({type:'new'});el('threads').onchange=()=>vscode.postMessage({type:'switch',id:el('threads').value});
for(const [id,type] of [['review','review'],['undo','undo'],['sourceControl','sourceControl']])el(id).onclick=()=>{el('actions').open=false;vscode.postMessage({type});};
for(const [id,text] of [['explain','Explain how this repository works. Cite the relevant files and lines.'],['repair','Run validation before editing. Investigate the failing unit tests, preserve existing developer work, and explain the proposed fix.']])el(id).onclick=()=>{el('input').value=text;el('input').oninput();el('input').focus();};
// Render a small safe inline subset. All model/repository text stays in text nodes.
function content(node,text){for(const part of text.split(/(\x60[^\x60\n]+\x60|\*\*[^*\n]+\*\*)/g)){const code=part.startsWith('\x60')&&part.endsWith('\x60');const bold=part.startsWith('**')&&part.endsWith('**');const span=document.createElement(code?'code':bold?'strong':'span');span.textContent=code?part.slice(1,-1):bold?part.slice(2,-2):part;node.append(span);}}
window.addEventListener('message',event=>{const m=event.data;if(m.type==='progress'){el('status').textContent=m.text;return;}if(m.type!=='state')return;
const switched=threadId!==m.thread.id,wasBusy=busy,follow=switched||nearBottom();
if(switched){if(threadId)drafts.set(threadId,el('input').value);threadId=m.thread.id;el('input').value=drafts.get(threadId)||'';resize();}
busy=m.busy;el('boundary').textContent=m.mode+' · '+(['Workspace','Full access'].includes(m.mode)?'Editing enabled':'Read-only');el('boundary').title=m.root;el('model').textContent=(m.root.split(/[\\/]/).pop()||m.root)+(m.model?' · '+m.model:'');el('model').title=m.root;
el('threads').replaceChildren();for(const t of m.threads){const o=document.createElement('option');o.value=t.id;o.textContent=t.name;o.selected=t.id===threadId;el('threads').append(o);}
const signature=JSON.stringify([threadId,m.thread.messages]);if(signature!==rendered){rendered=signature;el('messages').replaceChildren();for(const msg of m.thread.messages){const a=document.createElement('article');a.className=msg.role==='user'?'user':'assistant';const role=document.createElement('div');role.className='role';role.textContent=msg.role==='user'?'You':'Agent';const body=document.createElement('div');body.className='content';content(body,msg.content);a.append(role,body);el('messages').append(a);}el('empty').hidden=m.thread.messages.length>0;if(follow)bottom();else el('latest').hidden=false;}
for(const id of ['new','threads','sourceControl','explain','repair'])el(id).disabled=busy;el('review').disabled=busy||!m.thread.reviewTaskId;el('undo').disabled=busy||!m.thread.undoTaskId;el('status').className=busy?'working':'';
if(!busy)el('status').textContent=({complete:'Completed',cancelled:'Stopped',blocked:'Needs attention',failed:'Task failed',idle:'Ready'})[m.thread.status]||'Ready';else if(!wasBusy)el('status').textContent='Working…';refresh();
});vscode.postMessage({type:'ready'});
</script></body></html>`;
}
